#!/bin/bash

echo "🔍 Checking Server Logs for Conditional Routing"
echo "=============================================="
echo ""

echo "📋 Look for these log patterns in the server console:"
echo ""
echo "1. [Email] 🔍 RAW SETTINGS FROM XANO: {...}"
echo "2. [Email] 🔍 Processing X admin routes"
echo "3. [Email] 🔍 Checking route: {...}"
echo "4. [Email] 🔍 Comparing: {...}"
echo "5. [Email] 🔍 Route matches: true"
echo "6. [Email] ✅ Admin route matched - Field: ..."
echo "7. [Email] Sending to X admin recipient(s): [...]"
echo "8. [Email] ✅ Using CUSTOM HTML template for admin email"
echo "9. [Email] Sending email to: atownsend@hbiin.com"
echo "10. [Email] Subject: New submission from ..."
echo ""

echo "🐛 Common issues to look for:"
echo "- 'No notification settings configured for form'"
echo "- 'No admin routes configured and no fallback email set'"
echo "- 'No admin recipients found - no emails will be sent'"
echo "- SendGrid API errors"
echo "- Email validation errors"
echo ""

echo "📧 If emails are being sent but not received:"
echo "1. Check spam folder"
echo "2. Check SendGrid dashboard for delivery status"
echo "3. Verify email addresses are correct"
echo "4. Check if domain authentication is needed"
echo ""

echo "🔧 To test again:"
echo "1. Run: node debug-webhook-routing.js"
echo "2. Watch the server console for logs"
echo "3. Check email inboxes"
echo "4. Check spam folders"
